### ISSUE TITLE
Bug: TypeError: realpath is not a function

### ISSUE THREAD

**Issue by userings** [usabilityhub/ts-auto-guard#72]
running ```ts-auto-guard``` in cmdlet produces the following error:
```
(node:11252) UnhandledPromiseRejectionWarning: TypeError: realpath is not a function
    at visitDirectory (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:17838:45)
    at Object.matchFiles (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:17834:13)
    at Object.matchFiles (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\ts-simple-ast\dist\typescript\tsInternal.js:7:35)
    at Object.readDirectory (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\ts-simple-ast\dist\utils\compiler\readDirectory.js:16:27)
    at Object.readDirectory (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\ts-simple-ast\dist\utils\tsconfig\getTsParseConfigHost.js:11:37)
    at getFileNamesFromConfigSpecs (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:28531:40)
    at matchFileNames (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:28451:16)
    at getFileNames (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:28000:26)
    at parseJsonConfigFileContentWorker (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:27932:18)
    at Object.parseJsonConfigFileContent (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:27879:16)
```
node version v10.15.3 on windows.

**Comment by LeBeatle** [comment]
Hi,
i had the same Error and fixed it by hacking some Code in Typescript (this line: (C:\Users\admin\AppData\Roaming\npm\node_modules\ts-auto-guard\node_modules\typescript\lib\typescript.js:17838:45).

My edited Code is: 


        function visitDirectory(path, absolutePath, depth) {
            var canonicalPath = absolutePath;/*toCanonical(realpath(absolutePath));*/
            if (visited.has(canonicalPath))
                return;
            visited.set(canonicalPath, true);


I assume the Error could be because some Windows/Linux incompatibility. This made ts-auto-guard work for me and should not conflict with any other module. I hope I could help.

**Comment by davidmoshal** [comment]
tried that solution, didn't work for me, but it's not going to work with CI without some work.

**Comment by rhys-vdw** [comment]
Hey... I haven't touched this in a while. If anyone would like to get it up-to-date and running I can try to get write permissions for you.

**Comment by rhys-vdw** [comment]
It seems like this issue is coming from the `typescript` dependency... Perhaps it can be updated to latest?

**Comment by nhayashida** [comment]
@rhys-vdw It seems that this issue can be resolved by updating `ts-morph`.
Please check https://github.com/usabilityhub/ts-auto-guard/pull/76
